apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-grafana
  region: us-east-1

vpc:
  id: "vpc-0fa05ddd5e757c455"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      us-east-1a:
        id: "subnet-0a3cb433db534d0ed"
        cidr: "172.0.0.0/20" # (optional, must match CIDR used by the given subnet)

      us-east-1b:
        id: "subnet-03acf384462baaaa0"
        cidr: "172.0.32.0/20"  # (optional, must match CIDR used by the given subnet)



nodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
    privateNetworking: false # if only 'Private' subnets are given, this must be enabled